### ISSUE TITLE
Aborting lerna-audit (STRG+C) should restore original package.json

### ISSUE THREAD

**Issue by svettwer** [tnobody/lerna-audit#6]
As a user, I want lerna-audit to restore the original package.json in case I abort the process, so that my package.json is not corrupted. 

**Additional information**
When I abort the process currently, the resulting package.json lacks the lerna-internal-dependencies stored in memory. If you rerun the process, it might be successful, but the lerna-internal-dependencies are still lost. Therefore one should think about restoring the original package.json in case of a SIGKILL oder SIGINT.

**Comment by tnobody** [comment]
Resolved by #9
